version: '3.5'

services:
  mongodb:
    image: mongo:latest
    command: mongod --quiet --logpath /dev/null
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017

  node:
    build: 
      context: ./
      dockerfile: "node.dockerfile"
    hostname: nodeserver
    environment:
      - MONGODB_URI=mongodb://root:rootpassword@mongodb:27017
    depends_on:
      - mongodb
    ports:
      - 8080:8080
  
  